Repository John-Popovici/duel-of-the-eights, pull requests merged in 2025-04, with the labels that each got.

#336 📜 Added Up to Section 6 for Reflect and Trace Doc
  docs/ReflectAndTrace/ReflectAndTrace.pdf
  docs/ReflectAndTrace/ReflectAndTrace.tex
Labels: documentation

#337 📜 Added links to all changes in required docs
  docs/ReflectAndTrace/ReflectAndTrace.pdf
  docs/ReflectAndTrace/ReflectAndTrace.tex
Labels: documentation

#338 Client player name transfer dev
  server/main.gd
  server/room.gd
  src/NodeScene/blitz_game_settings.tscn
  src/NodeScene/bluff_game_settings.tscn
  src/NodeScene/custom_game_settings.tscn
  src/NodeScene/standard_game_settings.tscn
  src/Scripts/StandardVariants/variant_game_settings.gd
  src/Scripts/networkManager2P_Server.gd
Labels: bug

#339 🔨 Created new "Dice Storm"(yahtzee) hand
  src/Scripts/OnlineDefaultGameScene/OG_Dynamic_Scoreboard.gd
  src/Scripts/OnlineDefaultGameScene/OG_ScoreboardButton.gd
  src/Scripts/OnlineDefaultGameScene/OG_game_settings.gd
  src/Scripts/OnlineDefaultGameScene/OG_score_calculator.gd
  src/Scripts/StandardVariants/variant_game_settings.gd
Labels: feature
