Repository John-Popovici/duel-of-the-eights, pull requests merged in 2025-02, with the labels that each got.

#242 🐛 Fixing Saving Issues & Updating Presets & gitignore - resolves #239, closes #240
  .gitignore
  src/Presets/Images/profile_pic.png.import
  src/Presets/profile_settings.json
  src/Scripts/UniversalScripts/global_settings.gd
Labels: bug

#244 🐛 Dice Moved Aside Are Now Intangible - resolves #221
  src/Scripts/CustomDiceScripts/BaseDie.gd
  src/Scripts/CustomDiceScripts/CustomBaseDie.gd
  src/Scripts/OnlineDefaultGameScene/OG_dynamic_dice_container.gd
Labels: bug

#243 Game dev interrupt not polling
  src/Scripts/OnlineDefaultGameScene/OG_game_manager.gd
Labels: feature

#246 🔨 Added ambient audio controls to profile settings and pause menu with saving - closes #241
  src/Assets/Audio/SFX/switch_off.wav
  src/Assets/Audio/SFX/switch_off.wav.import
  src/Assets/Audio/SFX/switch_on.wav
  src/Assets/Audio/SFX/switch_on.wav.import
  src/NodeScene/game_manager.tscn
  src/NodeScene/player_profile_settings.tscn
  src/Scripts/OnlineDefaultGameScene/OG_game_ui.gd
  src/Scripts/PlayerProfile/player_profile_ui.gd
  src/Scripts/UniversalScripts/global_settings.gd
  src/Scripts/audio_manager.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: feature

#261 Game dev score preview fixed
  src/NodeScene/HandScoreEntry.tscn
  src/Scripts/OnlineDefaultGameScene/OG_ScoreboardButton.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: bug, feature

#262 🔨 Creating Tests for Dice Rolls and For Scoring - closes #248
  src/Scripts/UniversalScripts/scene_switcher.gd
  src/Tests/test_dice_container.gd
  src/Tests/test_scoring.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: feature

#263 🔨 Added overlay to help differentiate opponent dice, and added hover effects to users own dice ui - closes #214, closes #249
  src/NodeScene/dice_tex_temp.tscn
  src/NodeScene/game_manager.tscn
  src/Scripts/OnlineDefaultGameScene/OG_DiceDisplay.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: feature

#266 🔨 New chat toggle added to profile settings - closes #260
  src/NodeScene/player_profile_settings.tscn
  src/Scripts/OnlineDefaultGameScene/OG_game_ui.gd
  src/Scripts/PlayerProfile/player_profile_ui.gd
  src/Scripts/UniversalScripts/global_settings.gd
Labels: feature

#267 🔨 Implemented saving functionality for dice customization - closes #264
  .gitignore
  src/Presets/DiceTextures/READ_ME.txt
  src/Scripts/GlobalCustomization/GC_customization_ui.gd
  src/Scripts/UniversalScripts/global_settings.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: feature

#270 🔨 Enable saving for global theme preferences - closes #268
  .gitignore
  src/NodeScene/player_profile_settings.tscn
  src/Scripts/UniversalScripts/global_settings.gd
  src/Themes/Custom_Default/Custom_Default_Wood.tres
  src/Themes/Default_Pixel_Blue/Default_pixel_Blue.tres
  src/Themes/Default_Pixel_Wood/Default_pixel_.Wood.tres
Labels: feature
